/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface ManessingerComment {

    }
  }

  interface HTMLManessingerCommentElement extends StencilComponents.ManessingerComment, HTMLStencilElement {}

  var HTMLManessingerCommentElement: {
    prototype: HTMLManessingerCommentElement;
    new (): HTMLManessingerCommentElement;
  };
  interface HTMLElementTagNameMap {
    'manessinger-comment': HTMLManessingerCommentElement;
  }
  interface ElementTagNameMap {
    'manessinger-comment': HTMLManessingerCommentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'manessinger-comment': JSXElements.ManessingerCommentAttributes;
    }
  }
  namespace JSXElements {
    export interface ManessingerCommentAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;